# ********RoostGPT********

# Test generated by RoostGPT for test artillery-integration-test4_clone2 using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=e6f6028741
# ROOST_METHOD_SIG_HASH=cabc10e361
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Perform a GET request on the /query endpoint with an invalid API key',
#     steps: 'Given the base URL is "https://www.alphavantage.co"\n' +
#       'When I send a GET request to "/query" with query parameters:\n' +
#       '      | name     | value                       |\n' +
#       '      | symbol   | IBM                         |\n' +
#       '      | apikey   | invalid_key                 |\n' +
#       '      | function | TIME_SERIES_DAILY_ADJUSTED  |\n' +
#       'Then the response status code should not be 200\n' +
#       'And the response should indicate an error',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

  Background:
    * def FINNAB_9D4E0367FA_URL = karate.properties['FINNAB_9D4E0367FA_URL'] || karate.get('FINNAB_9D4E0367FA_URL', 'http://localhost:4010')
    * url FINNAB_9D4E0367FA_URL

  Scenario: Perform a GET request on the /query endpoint with an invalid API key
    Given path 'query'
    And params { symbol: 'IBM', apikey: 'invalid_key', function: 'TIME_SERIES_DAILY_ADJUSTED' }
    When method get
    Then match responseStatus != 200
  # The response should indicate an error
