# ********RoostGPT********

# Test generated by RoostGPT for test artillery-integration-test4_clone2 using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=d8145980b2
# ROOST_METHOD_SIG_HASH=0444ab87f6
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Perform a GET request on the /query endpoint with valid parameters',
#     steps: 'Given the base URL is "https://www.alphavantage.co"\n' +
#       'When I send a GET request to "/query" with query parameters:\n' +
#       '      | name     | value                       |\n' +
#       '      | symbol   | IBM                         |\n' +
#       '      | apikey   | demo                        |\n' +
#       '      | function | TIME_SERIES_DAILY_ADJUSTED  |\n' +
#       'Then the response status code should be 200\n' +
#       'And the response should contain valid data',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

  Background:
    * def FINNAB_9D4E0367FA_URL = karate.properties['FINNAB_9D4E0367FA_URL'] || karate.get('FINNAB_9D4E0367FA_URL', 'http://localhost:4010')

  Scenario: Perform a GET request on the /query endpoint with valid parameters
    * url FINNAB_9D4E0367FA_URL
    * path '/query'
    * params { symbol: 'IBM', apikey: 'demo', function: 'TIME_SERIES_DAILY_ADJUSTED' }
    * method get
    * status 200
    * match response contains { 'symbol': '#string', 'apikey': '#string', 'function': '#string' }
