# ********RoostGPT********

# Test generated by RoostGPT for test artillery-integration-test4_clone2 using AI Type  and AI Model 
# 
# ROOST_METHOD_HASH=048dec83b0
# ROOST_METHOD_SIG_HASH=8faff53a18
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Test API from Alphavantage.co',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Perform a GET request on the /query endpoint with no parameters',
#     steps: 'Given the base URL is "https://www.alphavantage.co"\n' +
#       'When I send a GET request to "/query" with no query parameters\n' +
#       'Then the response status code should be 200\n' +
#       'And the response should contain valid data',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Test API from Alphavantage.co

  Background:
    * def FINNAB_9D4E0367FA_URL = karate.properties['FINNAB_9D4E0367FA_URL'] || karate.get('FINNAB_9D4E0367FA_URL', 'http://localhost:4010')
    * url FINNAB_9D4E0367FA_URL

  Scenario: Perform a GET request on the /query endpoint with no parameters
    Given path 'query'
    When method get
    Then status 200
    And match $ == '#object'
