# ********RoostGPT********

# Test generated by RoostGPT for test amanJiraTesing using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointment/{appointmentId}_patch for http method type PATCH 
# RoostTestHash=a29ae50a32
# 
# 

# ********RoostGPT********
Feature: Appointment API

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def requestHeaders = { 'Authorization': '#(authToken)' }
    * configure headers = requestHeaders

  Scenario Outline: Verify appointment API responses
    Given path '/appointment/', '<appointmentId>'
    * def requestBody = <requestBody>
    * def expectedResponse = <expectedResponse>
    When method patch
    Then status <statusCode>
    And match response == expectedResponse

    Examples:
      | read('appointment_appointmentId_patch.csv') |
