# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointmentConfirmation_post for http method type POST 
# RoostTestHash=82449aeba3
# 
# 

# ********RoostGPT********
Feature: Appointment Confirmation

  Background:
    Given def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    And url urlBase
    And header Authorization = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test appointment confirmation with different payloads
    Given path '/appointmentConfirmation'
    And request '<requestBody>'
    When method post
    Then status <statusCode>
    And match response == '<responseBody>'

    Examples:
      | read('appointmentConfirmation_post.csv') |
