# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointment/{appointmentId}_patch for http method type PATCH 
# RoostTestHash=a29ae50a32
# 
# 

# ********RoostGPT********
Feature: Appointment API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def requestPayload = read('request-payload.json')
    * def expectedResponse = read('expected-response.json')

  Scenario Outline: Update Appointment
    Given path '/appointment/', '<appointmentId>'
    And header Authorization = authToken
    And request requestPayload
    When method patch
    Then status <statusCode>
    And match response == expectedResponse

    Examples:
      | read('appointment_appointmentId_patch.csv') |
