# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointment_post for http method type POST 
# RoostTestHash=bd2a92d273
# 
# 

# ********RoostGPT********
Feature: Appointment REST API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(AUTH_TOKEN)' }

  Scenario Outline: Post appointment and validate response
    Given path '/appointment'
    And request '<requestBody>'
    When method post
    Then status <statusCode>
    And match response == '<responseBody>'

    Examples:
      | read('appointment_post.csv') |
