# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointment/{appointmentId}_get for http method type GET 
# RoostTestHash=c9b995a56b
# 
# 

# ********RoostGPT********
Feature: Retrieve Appointment

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(AUTH_TOKEN)' }

  Scenario Outline: Retrieve appointment by appointmentId
    Given path 'appointment', '<appointmentId>'
    When method get
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('appointment_appointmentId_get.csv') |
