# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointment/{appointmentId}_delete for http method type DELETE 
# RoostTestHash=1052ba725b
# 
# 

# ********RoostGPT********
Feature: Appointment Management

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = {Authorization: '#(authToken)'}

  Scenario Outline: Delete Appointment
    Given path '/appointment/', appointmentId
    And param appointmentReason = '<appointmentReason>'
    And param appointmentComments = '<appointmentComments>'
    When method delete
    Then status <statusCode>
    And match response contains {type:'#(responseType)', code:'#(responseCode)', message:'#(responseMessage)'}

    Examples:
      | read('appointment_appointmentId_delete.csv') |
