# ********RoostGPT********

# Test generated by RoostGPT for test amanJiraTesing using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointment/{appointmentId}_delete for http method type DELETE 
# RoostTestHash=1052ba725b
# 
# 

# ********RoostGPT********
Feature: Appointment Management

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = authToken

  Scenario Outline: Delete Appointment
    Given path '/appointment/', '<appointmentId>'
    And param appointmentReason = 'Cancelamento Checkout'
    And param appointmentComments = 'Cancelamento Checkout'
    When method delete
    Then status <status>
    And match response.control.type == '#string'
    And match response.control.message == '#string'
    And match response.control.code == '#string'

    Examples:
      | read('appointment_appointmentId_delete.csv') |
