# ********RoostGPT********

# Test generated by RoostGPT for test amanJiraTesing using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /appointmentConfirmation_post for http method type POST 
# RoostTestHash=82449aeba3
# 
# 

# ********RoostGPT********
Feature: Appointment Confirmation

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * header Authorization = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test appointment confirmation endpoint
    Given path '/appointmentConfirmation'
    And request <payload>
    When method post
    Then status <status>
    And match response == <expectedResponse>

    Examples:
      | read('appointmentConfirmation_post.csv') |
