# ********RoostGPT********

# Test generated by RoostGPT for test amanJiraTesing using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=a43dbdd887
# 
# 

# ********RoostGPT********
Feature: Search Time Slot API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def auth = karate.properties['AUTH_TOKEN']
    * configure headers = {Authorization: '#(auth)'}

  Scenario Outline: Validate Search Time Slot API
    Given path '/searchTimeSlot'
    And param addressId = '<addressId>'
    And param subscriberId = '<subscriberId>'
    And param associatedDocument = '<associatedDocument>'
    And param startDate = '<startDate>'
    And param finishDate = '<finishDate>'
    And param orderType = '<orderType>'
    And param addressChangeFlag = '<addressChangeFlag>'
    And param productType = '<productType>'
    And param priorityFlag = '<priorityFlag>'
    And param priorityReason = '<priorityReason>'
    When method get
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('searchTimeSlot_get.csv') |
